@startuml TdtEnTDD
skinparam linetype ortho

'Relations :
'Un match a deux joueurs
Match "1" -- "2" Player
'Un match a de zéro à sept sets
Match "1" o-- "0..*" Set

class Player{
    -id : int
    -firstName : string
    -lastName : string
    -birthDate : DateTime
    -matchesWon : int
    -matchesPlayed : int
    -winPercentage : int
    -totalPointsWon : int
    -totalSetsWon : int
    -pointDiff : int
    -averagePointsPerSet : float
    -averagePointDiffPerSet : float
    -serviceErrors : int
    -elo : int
}

class Match{
    -identifier : int
    -name : string
    -date : DateTime
    -setCount : int
    -odd1 : float
    -odd2 : float
}

class Set{
    -identifier : int
    -player1Score : int
    -player2Score : int
    -player1ServiceErrors : int
    -player2ServiceErrors : int
}

@enduml